import app.utils.day_names as dn

ACTTYP = 'ActTyp'
ACTIVITY_TYPE = 'Activity type text'
PROJECT = 'Project'
REC_CCTR = 'Rec. CCtr'
RECEIVER_WBS = 'Receiver WBS element'
AATYPE = 'A/AType'
ATT_ABS_TYPE = 'Att./abs type text'
PROJECT_DESCRIPTION = 'Project description'
WBS_DESCRIPTION = 'WBS element description'
MU = 'MU'
TOTAL = 'Total'
MONDAY = dn.MONDAY
MONDAY_FROM = '%s - from' % dn.MONDAY
MONDAY_TO = '%s - to' % dn.MONDAY
TUESDAY = dn.TUESDAY
TUESDAY_FROM = '%s - from' % dn.TUESDAY
TUESDAY_TO = '%s - to' % dn.TUESDAY
WEDNESDAY = dn.WEDNESDAY
WEDNESDAY_FROM = '%s - from' % dn.WEDNESDAY
WEDNESDAY_TO = '%s - to' % dn.WEDNESDAY
THURSDAY = dn.THURSDAY
THURSDAY_FROM = '%s - from' % dn.THURSDAY
THURSDAY_TO = '%s - to' % dn.THURSDAY
FRIDAY = dn.FRIDAY
FRIDAY_FROM = '%s - from' % dn.FRIDAY
FRIDAY_TO = '%s - to' % dn.FRIDAY
SATURDAY = dn.SATURDAY
SATURDAY_FROM = '%s - from' % dn.SATURDAY
SATURDAY_TO = '%s - to' % dn.SATURDAY
SUNDAY = dn.SUNDAY
SUNDAY_FROM = '%s - from' % dn.SUNDAY
SUNDAY_TO = '%s - to' % dn.SUNDAY
