from app.option_preferences.column_layout.sap_column import SapColumn


DEFAULT_COLUMN_LAYOUT = [
    SapColumn('ActTyp', True, True, True, None, 0),
    SapColumn('Activity type text', True, True, False, '\t', 0),
    SapColumn('Rec. CCtr', True, True, True, None, 0),
    SapColumn('Receiver WBS element', True, True, True, None, 0),
    SapColumn('A/AType', True, True, True, None, 0),
    SapColumn('Att./abs. type text', True, True, False, '', 0),
    SapColumn('Project description', True, True, False, '', 0),
    SapColumn('WBS element description', True, True, False, '', 0),
    SapColumn('MU', True, True, True, None, 0),
    SapColumn('Total', True, True, False, '', 0),
    SapColumn('Monday', True, True, True, None, 0),
    SapColumn('Monday - from', True, True, True, None, 0),
    SapColumn('Monday - to', True, True, True, None, 0),
    SapColumn('Tuesday', True, True, True, None, 0),
    SapColumn('Tuesday - from', True, True, True, None, 0),
    SapColumn('Tuesday - to', True, True, True, None, 0),
    SapColumn('Wednesday', True, True, True, None, 0),
    SapColumn('Wednesday - from', True, True, True, None, 0),
    SapColumn('Wednesday - to', True, True, True, None, 0),
    SapColumn('Thursday', True, True, True, None, 0),
    SapColumn('Thursday - from', True, True, True, None, 0),
    SapColumn('Thursday - to', True, True, True, None, 0),
    SapColumn('Friday', True, True, True, None, 0),
    SapColumn('Friday - from', True, True, True, None, 0),
    SapColumn('Friday - to', True, True, True, None, 0),
    SapColumn('Saturday', True, True, True, None, 0),
    SapColumn('Saturday - from', True, True, True, None, 0),
    SapColumn('Saturday - to', True, True, True, None, 0),
    SapColumn('Sunday', True, True, True, None, 0),
    SapColumn('Sunday - from', True, True, True, None, 0),
    SapColumn('Sunday - to', True, True, True, None, 0),
]