from app.option_preferences.column_layout.column_names import *
from app.option_preferences.column_layout.sap_column import SapColumn


DEFAULT_COLUMN_LAYOUT = [
    SapColumn(ACTTYP, True, True, True, 0),
    SapColumn(ACTIVITY_TYPE, True, True, False, 0),
    SapColumn(REC_CCTR, True, True, True, 0),
    SapColumn(RECEIVER_WBS, True, True, True, 0),
    SapColumn(AATYPE, True, True, True, 0),
    SapColumn(ATT_ABS_TYPE, True, True, False, 0),
    SapColumn(PROJECT_DESCRIPTION, True, True, False, 0),
    SapColumn(WBS_DESCRIPTION, True, True, False, 0),
    SapColumn(MU, True, True, True, 0),
    SapColumn(TOTAL, True, True, False, 0),
    SapColumn(MONDAY, True, True, True, 0),
    SapColumn(MONDAY_FROM, True, True, True, 0),
    SapColumn(MONDAY_TO, True, True, True, 0),
    SapColumn(TUESDAY, True, True, True, 0),
    SapColumn(TUESDAY_FROM, True, True, True, 0),
    SapColumn(TUESDAY_TO, True, True, True, 0),
    SapColumn(WEDNESDAY, True, True, True, 0),
    SapColumn(WEDNESDAY_FROM, True, True, True, 0),
    SapColumn(WEDNESDAY_TO, True, True, True, 0),
    SapColumn(THURSDAY, True, True, True, 0),
    SapColumn(THURSDAY_FROM, True, True, True, 0),
    SapColumn(THURSDAY_TO, True, True, True, 0),
    SapColumn(FRIDAY, True, True, True, 0),
    SapColumn(FRIDAY_FROM, True, True, True, 0),
    SapColumn(FRIDAY_TO, True, True, True, 0),
    SapColumn(SATURDAY, True, True, True, 0),
    SapColumn(SATURDAY_FROM, True, True, True, 0),
    SapColumn(SATURDAY_TO, True, True, True, 0),
    SapColumn(SUNDAY, True, True, True, 0),
    SapColumn(SUNDAY_FROM, True, True, True, 0),
    SapColumn(SUNDAY_TO, True, True, True, 0),
]