# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'configure_columns_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(372, 320)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout.addWidget(self.checkBox_9, 0, QtCore.Qt.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3, 0, QtCore.Qt.AlignHCenter)
        self.checkBox_10 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_10.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout.addWidget(self.checkBox_10, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBox_18 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_18.setEnabled(False)
        self.checkBox_18.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_18.setChecked(True)
        self.checkBox_18.setObjectName("checkBox_18")
        self.horizontalLayout_7.addWidget(self.checkBox_18, 0, QtCore.Qt.AlignLeft)
        self.checkBox_19 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_19.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.horizontalLayout_7.addWidget(self.checkBox_19, 0, QtCore.Qt.AlignLeft)
        self.checkBox_20 = QtWidgets.QCheckBox(self.groupBox_4)
        self.checkBox_20.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_20.setCheckable(True)
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.horizontalLayout_7.addWidget(self.checkBox_20, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_8.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_4, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBox_21 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_21.setEnabled(False)
        self.checkBox_21.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_21.setChecked(True)
        self.checkBox_21.setObjectName("checkBox_21")
        self.horizontalLayout_8.addWidget(self.checkBox_21, 0, QtCore.Qt.AlignLeft)
        self.checkBox_22 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_22.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_22.setChecked(True)
        self.checkBox_22.setObjectName("checkBox_22")
        self.horizontalLayout_8.addWidget(self.checkBox_22, 0, QtCore.Qt.AlignLeft)
        self.checkBox_23 = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_23.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_23.setCheckable(True)
        self.checkBox_23.setChecked(True)
        self.checkBox_23.setObjectName("checkBox_23")
        self.horizontalLayout_8.addWidget(self.checkBox_23, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_9.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBox_7 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_7.setEnabled(False)
        self.checkBox_7.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_7.setChecked(True)
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_4.addWidget(self.checkBox_7, 0, QtCore.Qt.AlignLeft)
        self.checkBox_8 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_8.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_8.setChecked(True)
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_4.addWidget(self.checkBox_8, 0, QtCore.Qt.AlignLeft)
        self.checkBox_11 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_11.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_11.setCheckable(True)
        self.checkBox_11.setChecked(True)
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_4.addWidget(self.checkBox_11, 0, QtCore.Qt.AlignLeft)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_12 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_12.setEnabled(False)
        self.checkBox_12.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_12.setChecked(True)
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_5.addWidget(self.checkBox_12, 0, QtCore.Qt.AlignLeft)
        self.checkBox_13 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_13.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_13.setChecked(True)
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_5.addWidget(self.checkBox_13, 0, QtCore.Qt.AlignLeft)
        self.checkBox_14 = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_14.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_14.setCheckable(True)
        self.checkBox_14.setChecked(True)
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_5.addWidget(self.checkBox_14, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_6.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBox_24 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_24.setEnabled(False)
        self.checkBox_24.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_24.setChecked(True)
        self.checkBox_24.setObjectName("checkBox_24")
        self.horizontalLayout_9.addWidget(self.checkBox_24, 0, QtCore.Qt.AlignLeft)
        self.checkBox_25 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_25.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_25.setChecked(True)
        self.checkBox_25.setObjectName("checkBox_25")
        self.horizontalLayout_9.addWidget(self.checkBox_25, 0, QtCore.Qt.AlignLeft)
        self.checkBox_26 = QtWidgets.QCheckBox(self.groupBox_6)
        self.checkBox_26.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_26.setCheckable(True)
        self.checkBox_26.setChecked(True)
        self.checkBox_26.setObjectName("checkBox_26")
        self.horizontalLayout_9.addWidget(self.checkBox_26, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_10.addLayout(self.horizontalLayout_9, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_6, 2, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.checkBox_15 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_15.setEnabled(False)
        self.checkBox_15.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_15.setChecked(True)
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_6.addWidget(self.checkBox_15, 0, QtCore.Qt.AlignLeft)
        self.checkBox_16 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_16.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_16.setChecked(True)
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_6.addWidget(self.checkBox_16, 0, QtCore.Qt.AlignLeft)
        self.checkBox_17 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_17.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_17.setCheckable(True)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.horizontalLayout_6.addWidget(self.checkBox_17, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_7.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBox_33 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_33.setEnabled(False)
        self.checkBox_33.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_33.setChecked(True)
        self.checkBox_33.setObjectName("checkBox_33")
        self.horizontalLayout_12.addWidget(self.checkBox_33, 0, QtCore.Qt.AlignLeft)
        self.checkBox_34 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_34.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_34.setChecked(True)
        self.checkBox_34.setObjectName("checkBox_34")
        self.horizontalLayout_12.addWidget(self.checkBox_34, 0, QtCore.Qt.AlignLeft)
        self.checkBox_35 = QtWidgets.QCheckBox(self.groupBox_7)
        self.checkBox_35.setStyleSheet("QCheckBox::indicator {\n"
"     width: 12px;\n"
"     height: 12px;\n"
" }")
        self.checkBox_35.setCheckable(True)
        self.checkBox_35.setChecked(True)
        self.checkBox_35.setObjectName("checkBox_35")
        self.horizontalLayout_12.addWidget(self.checkBox_35, 0, QtCore.Qt.AlignLeft)
        self.gridLayout_11.addLayout(self.horizontalLayout_12, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_7, 3, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_5)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Configure Columns"))
        self.checkBox_2.setText(_translate("Dialog", "ActTyp"))
        self.checkBox_9.setText(_translate("Dialog", "A/AType"))
        self.checkBox.setText(_translate("Dialog", "Rec. CCtr"))
        self.checkBox_3.setText(_translate("Dialog", "Rec. WBS"))
        self.checkBox_10.setText(_translate("Dialog", "MU"))
        self.groupBox_4.setTitle(_translate("Dialog", "Thursday"))
        self.checkBox_18.setText(_translate("Dialog", "Date"))
        self.checkBox_19.setText(_translate("Dialog", "From"))
        self.checkBox_20.setText(_translate("Dialog", "To"))
        self.groupBox_5.setTitle(_translate("Dialog", "Friday"))
        self.checkBox_21.setText(_translate("Dialog", "Date"))
        self.checkBox_22.setText(_translate("Dialog", "From"))
        self.checkBox_23.setText(_translate("Dialog", "To"))
        self.groupBox.setTitle(_translate("Dialog", "Monday"))
        self.checkBox_7.setText(_translate("Dialog", "Date"))
        self.checkBox_8.setText(_translate("Dialog", "From"))
        self.checkBox_11.setText(_translate("Dialog", "To"))
        self.groupBox_2.setTitle(_translate("Dialog", "Tuesday"))
        self.checkBox_12.setText(_translate("Dialog", "Date"))
        self.checkBox_13.setText(_translate("Dialog", "From"))
        self.checkBox_14.setText(_translate("Dialog", "To"))
        self.groupBox_6.setTitle(_translate("Dialog", "Saturday"))
        self.checkBox_24.setText(_translate("Dialog", "Date"))
        self.checkBox_25.setText(_translate("Dialog", "From"))
        self.checkBox_26.setText(_translate("Dialog", "To"))
        self.groupBox_3.setTitle(_translate("Dialog", "Wednesday"))
        self.checkBox_15.setText(_translate("Dialog", "Date"))
        self.checkBox_16.setText(_translate("Dialog", "From"))
        self.checkBox_17.setText(_translate("Dialog", "To"))
        self.groupBox_7.setTitle(_translate("Dialog", "Sunday"))
        self.checkBox_33.setText(_translate("Dialog", "Date"))
        self.checkBox_34.setText(_translate("Dialog", "From"))
        self.checkBox_35.setText(_translate("Dialog", "To"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
